application: download-chromium
version: secure-python27
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: img
  secure: always

- url: .*
  script: main.app
  secure: always
